services:

    # original-autoheal:
    #     container_name: original-autoheal
    #     image: original-autoheal:latest
    #     platform: linux/arm64/v8
    #     build:
    #       context: .
    #       dockerfile: orig.Dockerfile

    lla-autoheal:
        container_name: lla-autoheal
        # extends:
        #   service: original-autoheal
        image: ${REGISTRY:-europe-west2-docker.pkg.dev/aero-chain-home/sspdar-client/}lla-autoheal:${VERSION:-latest}
        platform: linux/arm64/v8
        build:
            context: .
            dockerfile: ./lla.Dockerfile
            args:
                AUTOHEAL_VERSION: latest
        deploy:
            replicas: 1
        environment:
            AUTOHEAL_INTERVAL: 10
            AUTOHEAL_START_PERIOD: 10
            AUTOHEAL_ONLY_MONITOR_RUNNING: true
        network_mode: none
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        logging:
            options:
                max-size: "10M"
                max-file: "10"
